### PR TITLE
Use better relative imports for dummy namespace modules

### PR DESCRIPTION
**Pull request by ilevkivskyi**
This will cause generating the following content for e.g. `.../async.py`:
```python
# If you have issues importing this module because Python recognizes it as a keyword, use async_ instead.
from .async_ import *
```
Instead of
```python
# If you have issues importing this module because Python recognizes it as a keyword, use async_ instead.
from async_ import *
```
The former can cause troubles with mypy.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
I am trying to investigate the test failures in CI. Everything passes locally on my machine on both Python 3.6 and 3.7. Does anyone have any hints?

**Comment by greg-db** [comment]
@ilevkivskyi Can you share some more information about the issue? Is there any error output you can share?

**Comment by ilevkivskyi** [comment]
> Can you share some more information about the issue? Is there any error output you can share?

It is right here in Travis CI for this PR https://travis-ci.org/dropbox/stone/builds/533346407?utm_source=github_status&utm_medium=notification

Some failures look like an infra failure (you need to update Python version in requirements to run mypy). But there are also test failures I can't reproduce.

**Comment by greg-db** [comment]
Thanks! We'll take a look.

**Comment by ilevkivskyi** [comment]
I already pushed a CI update here.hopefully it will at least fix the mypy failures.

**Comment by ilevkivskyi** [comment]
OK, now the failures are only on Python 2 and PyPy 2.

**Comment by ilevkivskyi** [comment]
OK, all is green now.

**Pull request merged**
