### PR TITLE
Major code re-organization.

### PR DESCRIPTION
**Pull request by braincore**
Generally converted terminology to match standard compiler terms.
Stone has a frontend (lexer, parser, semantic analyzer, ir generator),
and a backend (generators that can IR -> target)

### CODE REVIEW

**Comment by braincore** [comment]
@scobbe: Hey, is private_field_support the only branch that'll be pained by this big re-org? Is there something else that might get clobbered?

**Comment by scobbe** [comment]
@braincore: `dropbox_internal` is the main branch we're using these days. `private_field_support` has some tests that `dropbox_internal` doesn't, but for the most part, it's `dropbox_internal`.

Also, thanks for doing a major code re-organization before we merged those branches lol

**Comment by braincore** [comment]
Haha, just trying to maximize overhead. I'm going to claim that this is an important lesson to avoid long-running forks--they never end well :)

What's with the "Generated from ..." commits on `dropbox_internal`?

**Comment by scobbe** [comment]
@braincore: Oh, that's why you haven't reviewed these PRs in months! You were trying to teach me a valuable lesson lol

The "Generated from ..." messages contain the `server` commit hash that I rsynced the Stone changes from. Sort of backwards from how we normally do it, but these days, we've been adding a feature to Stone in `server`, then dogfooding it internally, then rsyncing it to this branch.

**Pull request merged**
